# Generated by Django 3.1.7 on 2021-03-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.TextField(max_length=100)),
                ('Post_id', models.TextField(max_length=100)),
                ('Post', models.IntegerField()),
                ('Seguidores', models.IntegerField()),
                ('Seguindo', models.IntegerField()),
                ('Post_url', models.TextField(max_length=100)),
                ('img', models.TextField(max_length=100)),
                ('Likes', models.IntegerField()),
                ('Comments', models.IntegerField()),
                ('Periods', models.TextField(max_length=100)),
                ('update_time', models.TextField(max_length=100)),
            ],
        ),
    ]
